In [1]:
import h5py
import pandas as pd
import numpy as np

In [7]:
# Open both the raw and converted datasets
f_o = pd.read_hdf('zenodo/test.h5', key = 'table')
f_c = h5py.File('converted/test_c.h5', 'r')

For the raw dataset, each row is a jet and consists of 200 zero-padded constituents four-momenta. `ttv` specifies which dataset (train, test, validation) the jet is part of. `is_signal_new` is the truth label and indicates whether the jet originated from a top quark.

In [9]:
f_o

E_0        PX_0        PY_0        PZ_0         E_1        PX_1  \
436  218.364243 -172.341858  110.129105  -76.503624  153.661118 -111.320465   
440  122.238762   26.738468  -91.613998   76.382225  121.227135   17.644758   
441  383.772308  -97.906456   79.640709 -362.426361  200.625992  -54.921326   
444  132.492752  -77.763947  -87.322601  -62.304600   83.946594  -49.450481   
445  730.786987 -209.120010 -193.454315 -672.973877  225.477325  -75.363350   
..          ...         ...         ...         ...         ...         ...   
820  169.716614 -122.102844   36.656090  112.031059  112.158615  -80.692657   
822  287.591492  -81.565056 -140.493576  237.313202  160.357544  -34.246628   
824   91.996681   60.538616  -63.476665   27.734055   93.122139   60.690456   
825  132.474686   35.062359  125.736656   22.593466   61.466259    7.588309   
827   95.355087  -46.626762   25.236219   79.256989   86.610634  -36.374290   

          PY_1        PZ_1         E_2       PX_2  ...  E_199  PX_199  PY_199  \
436  93.167969  -50.390713   76.708054 -56.523701  ...    0.0     0.0     0.0   
440 -93.015450   75.715302   90.420105  21.377417  ...    0.0     0.0     0.0   
441  37.994343 -189.184753  123.247223 -33.828953  ...    0.0     0.0     0.0   
444 -53.823605  -41.288010   28.072624 -19.964916  ...    0.0     0.0     0.0   
445 -66.226990 -201.926651  217.040192 -63.698189  ...    0.0     0.0     0.0   
..         ...         ...         ...        ...  ...    ...     ...     ...   
820  24.224476   74.036636   86.687820 -60.876274  ...    0.0     0.0     0.0   
822 -88.843933  129.028931  105.006508 -30.313942  ...    0.0     0.0     0.0   
824 -61.697636   34.377369   67.617706  33.402180  ...    0.0     0.0     0.0   
825  55.307018   25.722607   53.369095  17.563345  ...    0.0     0.0     0.0   
827  28.903816   73.095024   76.419800 -39.889969  ...    0.0     0.0     0.0   

     PZ_199       truthE     truthPX     truthPY      truthPZ  ttv  \
436     0.0     0.000000    0.000000    0.000000     0.000000    1   
440     0.0     0.000000    0.000000    0.000000     0.000000    1   
441     0.0     0.000000    0.000000    0.000000     0.000000    1   
444     0.0     0.000000    0.000000    0.000000     0.000000    1   
445     0.0     0.000000    0.000000    0.000000     0.000000    1   
..      ...          ...         ...         ...          ...  ...   
820     0.0   832.899963 -572.147461  249.778381   524.242310    1   
822     0.0  1014.205322 -213.806396 -476.465851   852.417358    1   
824     0.0   659.905701  419.718506 -414.999115   239.802658    1   
825     0.0   659.797302   39.736858  593.325745   230.296585    1   
827     0.0  1255.107666 -514.749023  269.764374  1099.081665    1   

     is_signal_new  
436              0  
440              0  
441              0  
444              0  
445              0  
..             ...  
820              1  
822              1  
824              1  
825              1  
827              1  

[404000 rows x 806 columns]

The converted dataset is an numpy array in h5 format instead of a pandas dataframe. We list the keys and print a typical value for the key:

In [8]:
list(f_c.keys())

['Nobj', 'Pmu', 'is_signal', 'jet_pt', 'label', 'mass', 'truth_Pmu']

In [22]:
for key in f_c.keys():
    print(f_c[key][0])

17
[[ 2.18364243e+02 -1.72341858e+02  1.10129105e+02 -7.65036240e+01]
 [ 1.53661118e+02 -1.11320465e+02  9.31679688e+01 -5.03907127e+01]
 [ 7.67080536e+01 -5.65237007e+01  4.61272926e+01 -2.36953487e+01]
 [ 6.41816711e+01 -4.74191170e+01  3.87683411e+01 -1.91762753e+01]
 [ 5.79732666e+01 -4.18407707e+01  3.50211868e+01 -1.95899448e+01]
 [ 3.62938805e+01 -2.65304146e+01  2.19224472e+01 -1.15234156e+01]
 [ 1.09965315e+01 -2.71315145e+00  1.05449896e+01 -1.53808486e+00]
 [ 5.20679903e+00 -3.69272614e+00  3.01316810e+00 -2.09650874e+00]
 [ 4.95381403e+00 -3.36913300e+00  2.98500180e+00 -2.06856966e+00]
 [ 4.29062700e+00 -3.30971217e+00  2.35012317e+00 -1.39003766e+00]
 [ 3.79965448e+00 -2.70908237e+00  2.51254916e+00 -8.86196434e-01]
 [ 1.99092388e+00 -1.20586193e+00  1.21221972e+00 -1.01990104e+00]
 [ 1.70320201e+00 -1.24518943e+00  1.04613280e+00 -5.05970955e-01]
 [ 1.87011206e+00 -5.49257398e-01  1.39683723e+00 -1.11556327e+00]
 [ 1.32365847e+00 -8.94655287e-01  4.54673290e-01 -8.630966