In [1]:
import numpy as np
import h5py
import pandas as pd

In [4]:
hf = h5py.File('test_c.h5', 'r')

In [12]:
list(hf.keys())
NObj = hf['Nobj']
Pmu = hf['Pmu']
is_signal = hf['is_signal']
jet_pt = hf['jet_pt']
label = hf['label']
mass = hf['mass']
truth_Pmu = hf['truth_Pmu']
params = [NObj, Pmu, is_signal, jet_pt, label, mass, truth_Pmu]

In [15]:
for param in params:
    print(param.name)
    print(param.shape)
    print(param[0])
    print("===================================================================")

/Nobj
(404000,)
17
/Pmu
(404000, 200, 4)
[[ 2.18364243e+02 -1.72341858e+02  1.10129105e+02 -7.65036240e+01]
 [ 1.53661118e+02 -1.11320465e+02  9.31679688e+01 -5.03907127e+01]
 [ 7.67080536e+01 -5.65237007e+01  4.61272926e+01 -2.36953487e+01]
 [ 6.41816711e+01 -4.74191170e+01  3.87683411e+01 -1.91762753e+01]
 [ 5.79732666e+01 -4.18407707e+01  3.50211868e+01 -1.95899448e+01]
 [ 3.62938805e+01 -2.65304146e+01  2.19224472e+01 -1.15234156e+01]
 [ 1.09965315e+01 -2.71315145e+00  1.05449896e+01 -1.53808486e+00]
 [ 5.20679903e+00 -3.69272614e+00  3.01316810e+00 -2.09650874e+00]
 [ 4.95381403e+00 -3.36913300e+00  2.98500180e+00 -2.06856966e+00]
 [ 4.29062700e+00 -3.30971217e+00  2.35012317e+00 -1.39003766e+00]
 [ 3.79965448e+00 -2.70908237e+00  2.51254916e+00 -8.86196434e-01]
 [ 1.99092388e+00 -1.20586193e+00  1.21221972e+00 -1.01990104e+00]
 [ 1.70320201e+00 -1.24518943e+00  1.04613280e+00 -5.05970955e-01]
 [ 1.87011206e+00 -5.49257398e-01  1.39683723e+00 -1.11556327e+00]
 [ 1.32365847e+00 -8.